# Generated by Django 5.1.5 on 2025-01-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Profissional')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Profissional')),
                ('telefone_whatsapp', models.CharField(max_length=15, unique=True, verbose_name='WhatsApp')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço')),
                ('horario_atendimento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Atendimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profissional', verbose_name='Profissional')),
            ],
        ),
    ]
