# Generated by Django 5.1.5 on 2025-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='horario_atendimento',
            new_name='horario_inicio',
        ),
        migrations.AddField(
            model_name='servico',
            name='horario_fim',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Atendimento'),
        ),
    ]
