# Generated by Django 5.1.5 on 2025-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_horario_atendimento_servico_horario_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='horario_fim',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='Horário de Atendimento'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='horario_inicio',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='Horário de Atendimento'),
        ),
    ]
