# Generated by Django 5.1.5 on 2025-01-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profissional_options_alter_servico_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='horario_fim',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='Horário término de Atendimento'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='horario_inicio',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='Horário início de Atendimento'),
        ),
    ]
