# Generated by Django 5.1.5 on 2025-01-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_servico_horario_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='telefone_whatsapp',
            field=models.CharField(max_length=16, unique=True, verbose_name='WhatsApp'),
        ),
    ]
