# Generated by Django 5.1.5 on 2025-01-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profissional_foto_servico_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Imagem')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galerias', verbose_name='Imagem da Galeria')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
            },
        ),
        migrations.AlterField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição do Profissional'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição do Serviço'),
        ),
    ]
