# Generated by Django 5.1.5 on 2025-01-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_galeira_alter_profissional_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeira',
            options={'verbose_name': 'Galeria'},
        ),
    ]
