# Generated by Django 5.1.5 on 2025-01-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_galeira_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeira',
            options={},
        ),
    ]
