# Generated by Django 5.1.5 on 2025-01-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_galeira_galeria_alter_galeria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerias'},
        ),
    ]
